<a href="https://colab.research.google.com/github/ronakraj00/data_mining_lab/blob/main/demo_ronak_raj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
data=np.genfromtxt('demodata.csv',delimiter=',')

In [3]:
data

array([[14.    ,  3.    ,  0.    , ...,  4.    ,  1.5714,  0.    ],
       [ 5.    ,  3.    ,  0.    , ...,  1.    ,  0.8   ,  0.    ],
       [13.    ,  1.    ,  1.    , ...,  1.    ,  0.7692,  0.    ],
       ...,
       [23.    ,  1.    ,  0.    , ..., 24.    ,  2.3043,  0.    ],
       [11.    ,  1.    ,  8.    , ..., 22.    ,  4.6364,  1.    ],
       [ 4.    ,  2.    ,  0.    , ...,  5.    ,  1.75  ,  0.    ]])

In [4]:
np.shape(data)

(356, 21)

In [5]:
np.shape(data)[0]

356

In [6]:
np.shape(data)[1]

21

In [7]:
np.shape(data)[1]-1

20

In [8]:
np.sum(data)

175661.11242000002

In [9]:
np.sum(data,axis=0)

array([3.7360000e+03, 8.0800000e+02, 2.0800000e+02, 3.8280000e+03,
       1.2046000e+04, 2.6380000e+04, 2.0260000e+03, 1.9400000e+03,
       2.9180000e+03, 3.3208540e+02, 1.0839000e+05, 2.4984470e+02,
       2.4200000e+02, 1.6639418e+02, 1.7374474e+02, 2.3600000e+02,
       3.7600000e+02, 9.4926294e+03, 1.5420000e+03, 4.9041400e+02,
       8.0000000e+01])

In [10]:
np.sum(data,axis=1)

array([5.41286220e+02, 4.13502440e+02, 2.27282050e+02, 3.83850690e+02,
       1.16068377e+03, 5.88345090e+02, 2.54984090e+02, 8.19583300e+01,
       1.61280580e+02, 9.67234750e+02, 2.32685930e+02, 1.64150584e+03,
       2.43615090e+02, 7.00601240e+02, 6.47428620e+02, 8.65897500e+01,
       1.17576597e+03, 7.06153900e+01, 2.37920300e+02, 2.60627390e+02,
       3.29341670e+02, 7.41666700e+01, 1.62166340e+02, 5.61809060e+02,
       8.98190410e+02, 3.78755200e+02, 1.91737031e+03, 1.21333330e+02,
       5.87245500e+02, 8.99583300e+01, 2.20000000e+01, 1.99400000e+02,
       5.47083300e+01, 1.03318998e+03, 3.19380400e+02, 4.76250000e+01,
       2.63071860e+02, 6.50456950e+02, 1.33183330e+02, 9.64824880e+02,
       4.35417970e+02, 2.90000000e+01, 7.70000000e+01, 2.67398500e+02,
       3.78750000e+01, 1.63064220e+02, 1.77812462e+03, 3.69089720e+02,
       1.52324651e+03, 1.82850000e+02, 6.80076630e+02, 7.07177400e+01,
       2.19633330e+02, 2.80000000e+01, 7.01666700e+01, 1.42114530e+02,
      

In [11]:
np.max(data)

2446.0

In [12]:
np.min(data)

0.0

In [13]:
np.mean(data)

23.496671003210274

In [14]:
np.min(data,axis=0)

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.])

In [15]:
np.min(data,axis=1)

array([0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.19333, 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.  

In [16]:
np.max(data,axis=1)

array([3.850e+02, 2.760e+02, 1.110e+02, 2.650e+02, 7.470e+02, 4.370e+02,
       1.470e+02, 3.300e+01, 9.500e+01, 7.300e+02, 1.470e+02, 1.156e+03,
       1.490e+02, 4.480e+02, 4.930e+02, 3.100e+01, 7.190e+02, 3.200e+01,
       1.280e+02, 1.680e+02, 2.150e+02, 3.900e+01, 1.000e+02, 3.660e+02,
       5.600e+02, 2.650e+02, 1.489e+03, 6.900e+01, 4.040e+02, 3.700e+01,
       5.000e+00, 1.370e+02, 2.400e+01, 6.590e+02, 1.740e+02, 1.600e+01,
       1.730e+02, 1.640e+02, 5.500e+01, 5.270e+02, 2.790e+02, 9.000e+00,
       2.100e+01, 1.510e+02, 6.000e+00, 8.700e+01, 8.020e+02, 2.430e+02,
       1.260e+03, 5.900e+01, 5.170e+02, 2.800e+01, 1.440e+02, 5.000e+00,
       3.400e+01, 8.100e+01, 7.370e+02, 3.960e+02, 3.300e+01, 4.800e+01,
       6.800e+01, 2.446e+03, 3.590e+02, 2.000e+01, 6.080e+02, 1.520e+02,
       5.570e+02, 5.140e+02, 2.770e+02, 5.900e+01, 3.770e+02, 4.000e+00,
       2.940e+02, 1.760e+02, 4.620e+02, 3.940e+02, 7.480e+02, 7.800e+01,
       6.770e+02, 4.660e+02, 1.423e+03, 2.300e+01, 

In [17]:
np.max(data,axis=0)

array([7.7000e+01, 6.0000e+00, 4.0000e+01, 1.3600e+02, 1.9600e+02,
       2.4460e+03, 1.3500e+02, 2.8000e+01, 6.8000e+01, 2.0000e+00,
       2.0400e+03, 1.0000e+00, 9.0000e+00, 1.0000e+00, 1.0000e+00,
       4.0000e+00, 1.1000e+01, 2.0817e+02, 3.5000e+01, 6.0870e+00,
       1.0000e+00])

In [18]:
np.var(data)

14120.291116690029

In [19]:
np.std(data)

118.82883116773483

In [20]:
np.median(data)

1.0

In [21]:
data[2][0]

13.0

In [22]:
data[2][3]

8.0

In [23]:
data[2,3]

8.0

In [24]:
data[2: ,3]

array([  8.,   7.,   6.,   3.,   3.,   6.,   6.,  18.,   8.,  15.,   5.,
        30.,   8.,  10.,  33.,   3.,   9.,   9.,   5.,   1.,   2.,  11.,
        24.,   2.,  25.,   5.,   7.,   6.,   1.,   2.,   4.,  27.,  20.,
         2.,   7., 100.,  19.,   3.,   9.,   9.,  11.,   8.,   5.,   6.,
        19.,  12.,   2.,  59.,  11.,   3.,   4.,   4.,   3.,   1.,  13.,
         5.,   3.,   5.,   1., 120.,   5.,   1.,  13.,   8.,  10.,  19.,
         9.,  21.,   4.,   4.,  11.,   5.,   5.,   7.,   7.,   5.,   7.,
        10.,  21.,   3.,   7.,   1.,  13.,   4.,   7.,   8.,  31.,  18.,
         4.,   8.,   2.,  11.,  10.,   8.,   3.,   4.,   9.,  10.,   6.,
         9.,   6.,  10.,   1.,   8.,   3.,  17.,   7.,  10.,  28.,  15.,
         5.,   4.,   9.,  12.,  12.,  10.,   2., 136.,   7.,   7.,  24.,
        16.,   3.,   2.,   9.,  10.,   2.,   3.,   6.,  11.,   4.,   7.,
         7.,   3.,   1.,   7.,   3.,  11.,  58.,   8.,   7.,   9.,   2.,
         6.,   0.,  14.,   5.,   0.,   1.,  24.,  1

In [25]:
data[-1: ,3]

array([3.])

In [26]:
data[: ,-1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1.,
       0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0.

In [27]:
data[300: , 1]

array([1., 3., 6., 3., 2., 2., 2., 3., 1., 3., 6., 1., 4., 1., 2., 1., 3.,
       1., 1., 3., 2., 2., 1., 1., 1., 4., 3., 1., 1., 4., 4., 1., 2., 1.,
       3., 1., 2., 4., 2., 3., 1., 1., 3., 3., 3., 1., 1., 1., 3., 1., 3.,
       3., 1., 1., 1., 2.])

In [28]:
data[: ,20]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1.,
       0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0.

In [29]:
np.sum(data[: ,-1])

80.0

In [30]:
np.sum(data,axis=0)[-1]

80.0

In [31]:
np.argmax(data,axis=0)

array([110,  43,  37, 119, 110,  61, 119, 110, 110,   7, 110,   0, 110,
        30,   7,  43,  16,  48,  26,  26,   9])

In [32]:
np.argmin(data,axis=1)

array([ 2,  2, 12,  2,  2,  2,  2,  2,  2, 14,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2, 20,  2,  2, 12,  2,  2,  2,  2,  2,  2,  2,
        5,  2,  2, 20,  2,  2, 12,  2,  2,  2,  2,  2,  2,  2,  2,  5,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2, 12,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 12,  2,  2,  0,  2,
        2,  2,  2,  5, 15,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        5,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 20,  2,  2,
        2,  2,  2,  2, 14,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  5,  2,  2, 20,  2,  2,  2,  2,  2,  2,  0,  2, 14,  2,
        2,  2,  2,  2,  2, 15,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  0,  2,  2, 13,  2, 13,  2,  2,  2, 12,  2,  2,  2,  2,  2,  2,
       14,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 20,  2,  2,
       12,  2,  2,  2,  2,  2,  2,  2,  5,  2,  2, 20,  2,  2, 12,  2,  2,
        2,  2,  2,  2,  2

In [33]:
a=np.array([3,4,6,7,8,9])


In [34]:
print(a)

[3 4 6 7 8 9]


In [35]:
b=np.sort(a)

In [36]:
print(b)

[3 4 6 7 8 9]


In [37]:
c=np.argsort(a)
print(c)

[0 1 2 3 4 5]


In [38]:
print(a[c])

[3 4 6 7 8 9]


In [39]:
b=np.sort(a*-1)
print(b)

[-9 -8 -7 -6 -4 -3]


In [40]:
c=np.argsort(a*-1)
print(c)

[5 4 3 2 1 0]


In [41]:
print(a[c])

[9 8 7 6 4 3]


In [42]:
np.where(a>=3)

(array([0, 1, 2, 3, 4, 5]),)

In [43]:
np.where(a>=3)[0]

array([0, 1, 2, 3, 4, 5])

In [44]:
e=np.where(a>=3)[0]
print(len(e))

6


In [45]:
l=len(np.where((data[: ,-1])==1)[0])
print(l)

80


In [46]:
np.savetxt('test_data.csv',data[:,5:10],delimiter=',' ,fmt='%f')

In [47]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [48]:
floc='/content/drive/MyDrive/data_mining_lab/'

In [49]:
import math
def civ(cgpa):
  cv=np.zeros((2))
  mx=np.mean(cgpa)
  sx=np.std(cgpa)
  lx=len(cgpa)
  cv[0]=mx-1.96*sx/math.sqrt(lx)
  cv[1]=mx+1.96*sx/math.sqrt(lx)
  return cv

In [50]:
fname=floc+'1.csv'
data=np.genfromtxt(fname,delimiter=',')

In [51]:
cv=civ(data[:,0])

In [52]:
for i in range(1,33):
  print('College',i)
  fname=floc+str(i)+'.csv'
  data=np.genfromtxt(fname,delimiter=',')
  print('no of students',np.shape(data)[0],'waiting',np.sum(data[:,-1]))
  cvf=np.zeros((np.shape(data)[1]-1,4))
  in1=np.where(data[:,-1]==0)
  in2=np.where(data[:,-1]==1)
  for j in range(0,np.shape(data)[1]-1):
    fv=data[:,j]
    cvf[j,0:2]=civ(fv[in1[0]])
    cvf[j,2:4]=civ(fv[in2[0]])
  fname=floc+'civ_'+str(i)+'.csv'
  np.savetxt(fname,cvf,delimiter=',',fmt='%f')

College 1
no of students 125 waiting 20.0
College 2
no of students 178 waiting 40.0
College 3
no of students 293 waiting 32.0
College 4
no of students 351 waiting 92.0
College 5
no of students 745 waiting 166.0
College 6
no of students 234 waiting 27.0
College 7
no of students 608 waiting 216.0
College 8
no of students 872 waiting 145.0
College 9
no of students 965 waiting 188.0
College 10
no of students 111 waiting 63.0
College 11
no of students 352 waiting 40.0
College 12
no of students 272 waiting 90.0
College 13
no of students 306 waiting 75.0
College 14
no of students 312 waiting 79.0
College 15
no of students 367 waiting 48.0
College 16
no of students 135 waiting 34.0
College 17
no of students 109 waiting 37.0
College 18
no of students 205 waiting 189.0
College 19
no of students 195 waiting 91.0
College 20
no of students 247 waiting 144.0
College 21
no of students 340 waiting 203.0
College 22
no of students 660 waiting 66.0
College 23
no of students 176 waiting 27.0
College 24
no

In [53]:
from matplotlib import pyplot
for i in range(1,33):
  fname=floc+str(i)+'.csv'
  print(fname)
  data=np.genfromtxt(fname,delimiter=',')
  pyplot.figure(figsize=(15,12))
  for j in range(0,20):
    fv=data[:,j]
    in1=np.where(data[:,-1]==0)
    in2=np.where(data[:,-1]==1)
    cv=np.zeros((2,2))
    cv[:,0]=civ(data[in1[0],j])
    cv[:,1]=civ(data[in2[0],j])
    pyplot.subplot(4,5,j+1)
    pyplot.boxplot(cv,labels=['JOB','No-JOB'])
    pyplot.ylabel('Features_'+str(j+1))
    pyplot.grid(True)
  pyplot.savefig(floc+'CIV_'+str(i)+'.jpg')
  pyplot.close()

/content/drive/MyDrive/data_mining_lab/1.csv
/content/drive/MyDrive/data_mining_lab/2.csv
/content/drive/MyDrive/data_mining_lab/3.csv
/content/drive/MyDrive/data_mining_lab/4.csv
/content/drive/MyDrive/data_mining_lab/5.csv
/content/drive/MyDrive/data_mining_lab/6.csv
/content/drive/MyDrive/data_mining_lab/7.csv
/content/drive/MyDrive/data_mining_lab/8.csv
/content/drive/MyDrive/data_mining_lab/9.csv
/content/drive/MyDrive/data_mining_lab/10.csv
/content/drive/MyDrive/data_mining_lab/11.csv
/content/drive/MyDrive/data_mining_lab/12.csv
/content/drive/MyDrive/data_mining_lab/13.csv
/content/drive/MyDrive/data_mining_lab/14.csv
/content/drive/MyDrive/data_mining_lab/15.csv
/content/drive/MyDrive/data_mining_lab/16.csv
/content/drive/MyDrive/data_mining_lab/17.csv
/content/drive/MyDrive/data_mining_lab/18.csv
/content/drive/MyDrive/data_mining_lab/19.csv
/content/drive/MyDrive/data_mining_lab/20.csv
/content/drive/MyDrive/data_mining_lab/21.csv
/content/drive/MyDrive/data_mining_lab/22.c

In [54]:
from scipy import stats
stats.norm.sf(1.96)*2

0.04999579029644087

In [55]:
for i in range(1, 33):
    fname = floc + str(i) + '.csv'
    print(fname)
    data = np.genfromtxt(fname, delimiter=',')

    pyplot.figure(figsize=(15, 12))

    for j in range(20):
        fv = data[:, j]
        in1 = np.where(data[:, -1] == 0)
        in2 = np.where(data[:, -1] == 1)

        cv = np.zeros((2, 2))
        cv[:, 0] = civ(data[in1[0], j])
        cv[:, 1] = civ(data[in2[0], j])

        pyplot.subplot(4, 5, j + 1)
        pyplot.boxplot(cv, labels=['No-JOB', 'JOB'])
        pyplot.ylabel(f'Features_{j+1}')
        pyplot.grid(True)

    pyplot.savefig(floc + 'CIV_' + str(i) + '.jpg')
    pyplot.close()

/content/drive/MyDrive/data_mining_lab/1.csv
/content/drive/MyDrive/data_mining_lab/2.csv
/content/drive/MyDrive/data_mining_lab/3.csv
/content/drive/MyDrive/data_mining_lab/4.csv
/content/drive/MyDrive/data_mining_lab/5.csv
/content/drive/MyDrive/data_mining_lab/6.csv
/content/drive/MyDrive/data_mining_lab/7.csv
/content/drive/MyDrive/data_mining_lab/8.csv
/content/drive/MyDrive/data_mining_lab/9.csv
/content/drive/MyDrive/data_mining_lab/10.csv
/content/drive/MyDrive/data_mining_lab/11.csv
/content/drive/MyDrive/data_mining_lab/12.csv
/content/drive/MyDrive/data_mining_lab/13.csv
/content/drive/MyDrive/data_mining_lab/14.csv
/content/drive/MyDrive/data_mining_lab/15.csv
/content/drive/MyDrive/data_mining_lab/16.csv
/content/drive/MyDrive/data_mining_lab/17.csv
/content/drive/MyDrive/data_mining_lab/18.csv
/content/drive/MyDrive/data_mining_lab/19.csv
/content/drive/MyDrive/data_mining_lab/20.csv
/content/drive/MyDrive/data_mining_lab/21.csv
/content/drive/MyDrive/data_mining_lab/22.c

In [56]:
def zvalue(x1, x2):
    mx1 = np.mean(x1)
    mx2 = np.mean(x2)
    if mx1 == 0 and mx2 == 0:
        return 0, 1
    sx1 = np.std(x1)
    sx2 = np.std(x2)
    n1 = len(x1)
    n2 = len(x2)

    zv = (mx1 - mx2) / (math.sqrt(sx1**2 / n1 + sx2**2 / n2))
    zv = np.abs(zv)

    pv = stats.norm.sf(zv) * 2
    return zv, pv

In [57]:
from statsmodels.stats.weightstats import ztest

def zvalue1(x1, x2):
    zv, pv = ztest(x1, x2)
    return zv, pv

In [58]:
def zall(data):
    zv = np.zeros((20))
    pv = np.zeros((20))

    in1 = np.where(data[:, -1] == 0)
    in2 = np.where(data[:, -1] == 1)

    for j in range(20):
        x1 = data[in1[0], j]
        x2 = data[in2[0], j]
        zv[j], pv[j] = zvalue(x1, x2)

    return zv, pv

In [59]:
for i in range(1, 33):
    fname = floc + str(i) + '.csv'
    data = np.genfromtxt(fname, delimiter=',')

    zv, pv = zall(data)

    in1 = np.where(pv <= 0.05)[0]
    print(f"College=={i} No of Features={len(in1)}")

    datan = data[:, in1]
    datan = np.concatenate((datan, data[:, -1].reshape(-1, 1)), axis=1)

    fname = floc + str(32 + i) + '.csv'
    np.savetxt(fname, datan, delimiter=',', fmt='%f')

College==1 No of Features=8
College==2 No of Features=3
College==3 No of Features=13
College==4 No of Features=14
College==5 No of Features=16
College==6 No of Features=11
College==7 No of Features=10
College==8 No of Features=16
College==9 No of Features=17
College==10 No of Features=11
College==11 No of Features=14
College==12 No of Features=16
College==13 No of Features=15
College==14 No of Features=17
College==15 No of Features=14
College==16 No of Features=13
College==17 No of Features=11
College==18 No of Features=7
College==19 No of Features=14
College==20 No of Features=10
College==21 No of Features=16
College==22 No of Features=14
College==23 No of Features=9
College==24 No of Features=14
College==25 No of Features=15
College==26 No of Features=15
College==27 No of Features=11
College==28 No of Features=12
College==29 No of Features=1
College==30 No of Features=15
College==31 No of Features=18
College==32 No of Features=7


In [60]:
def rst(data):
    zv = np.zeros((20))
    pv = np.zeros((20))

    in1 = np.where(data[:, -1] == 0)
    in2 = np.where(data[:, -1] == 1)

    for j in range(20):
        x1 = data[in1[0], j]
        x2 = data[in2[0], j]
        zv[j], pv[j] = stats.ranksums(x1, x2)

    return zv, pv

In [61]:
for i in range(1, 33):
    fname = floc + str(i) + '.csv'

    try:
        data = np.genfromtxt(fname, delimiter=',')
        zv, pv = rst(data)

        in1 = np.where(pv <= 0.05)[0]
        print(f"College=={i} No of Features={len(in1)}")

        datan = data[:, in1]  # Select significant features
        datan = np.concatenate((datan, data[:, -1].reshape(-1, 1)), axis=1)  # Add the label column

        fname = floc + str(32 * 2 + i) + '.csv'
        np.savetxt(fname, datan, delimiter=',', fmt='%f')

    except Exception as e:
        print(f"Error processing file {fname}: {e}")

College==1 No of Features=12
College==2 No of Features=2
College==3 No of Features=13
College==4 No of Features=14
College==5 No of Features=16
College==6 No of Features=10
College==7 No of Features=9
College==8 No of Features=16
College==9 No of Features=16
College==10 No of Features=9
College==11 No of Features=13
College==12 No of Features=18
College==13 No of Features=15
College==14 No of Features=14
College==15 No of Features=14
College==16 No of Features=13
College==17 No of Features=12
College==18 No of Features=4
College==19 No of Features=12
College==20 No of Features=12
College==21 No of Features=17
College==22 No of Features=15
College==23 No of Features=8
College==24 No of Features=14
College==25 No of Features=15
College==26 No of Features=13
College==27 No of Features=14
College==28 No of Features=12
College==29 No of Features=2
College==30 No of Features=15
College==31 No of Features=16
College==32 No of Features=6


In [62]:
def ccra(data):
    r = np.corrcoef(data[:, :-1], rowvar=False)
    r = np.abs(r)
    imp = np.ones(np.shape(data)[1] - 1)
    for i in range(np.shape(data)[1] - 1):
        if imp[i] == 1:
            in1 = np.where(r[i, i+1:] >= 0.7)
            imp[in1[0] + (i + 1)] = 0
    return imp



In [63]:
imp = ccra(data)
in1 = np.where(imp == 1)
newData = data[:, in1[0]]


r_new = np.corrcoef(newData, rowvar=False)
r_new=abs(r_new)

for i in range(len(in1[0])-1):
    print(np.max(r_new[i,i+1:]))


0.6711247847851938
0.553099356585198
0.319064215449279
0.4968824386054965
0.6615673910282225
0.47910123586166126
0.42326340793418293
0.034095741843165446
0.15685221424735435


In [64]:
for i in range(1,33):
  fname=floc+str(i)+'.csv'
  data=np.genfromtxt(fname,delimiter=',')
  pv=ccra(data)
  in1=np.where(pv==1)
  print("College==",i,"No of Features=",len(in1[0]))
  datan=data[:,in1[0]]
  datan=np.concatenate((datan,data[:,-1].reshape(-1,1)),axis=1)
  fname=floc+str(32*3+i)+'.csv'
  np.savetxt(fname,datan,delimiter=',',fmt='%f')

College== 1 No of Features= 10
College== 2 No of Features= 11
College== 3 No of Features= 11
College== 4 No of Features= 11
College== 5 No of Features= 10
College== 6 No of Features= 12
College== 7 No of Features= 11
College== 8 No of Features= 11
College== 9 No of Features= 12
College== 10 No of Features= 10
College== 11 No of Features= 11
College== 12 No of Features= 12
College== 13 No of Features= 11
College== 14 No of Features= 11
College== 15 No of Features= 11
College== 16 No of Features= 12
College== 17 No of Features= 14
College== 18 No of Features= 11
College== 19 No of Features= 12
College== 20 No of Features= 11
College== 21 No of Features= 11
College== 22 No of Features= 12
College== 23 No of Features= 11
College== 24 No of Features= 12
College== 25 No of Features= 12
College== 26 No of Features= 11
College== 27 No of Features= 11
College== 28 No of Features= 11


/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]


College== 29 No of Features= 11
College== 30 No of Features= 11
College== 31 No of Features= 12
College== 32 No of Features= 10


In [65]:
for i in range(1,33):
  fname=floc+str(32*2+i)+'.csv'
  data=np.genfromtxt(fname,delimiter=',')
  pv=ccra(data)
  in1=np.where(pv==1)
  print("College==",i,"No of Features=",len(in1[0]))
  datan=data[:,in1[0]]
  datan=np.concatenate((datan,data[:,-1].reshape(-1,1)),axis=1)
  fname=floc+str(32*4+i)+'.csv'
  np.savetxt(fname,datan,delimiter=',',fmt='%f')

College== 1 No of Features= 6
College== 2 No of Features= 2
College== 3 No of Features= 9
College== 4 No of Features= 9
College== 5 No of Features= 8
College== 6 No of Features= 6
College== 7 No of Features= 3
College== 8 No of Features= 9
College== 9 No of Features= 9
College== 10 No of Features= 3
College== 11 No of Features= 8
College== 12 No of Features= 11
College== 13 No of Features= 8
College== 14 No of Features= 8
College== 15 No of Features= 7
College== 16 No of Features= 7
College== 17 No of Features= 8
College== 18 No of Features= 3
College== 19 No of Features= 10
College== 20 No of Features= 6
College== 21 No of Features= 10
College== 22 No of Features= 9
College== 23 No of Features= 5
College== 24 No of Features= 10
College== 25 No of Features= 9
College== 26 No of Features= 7
College== 27 No of Features= 9
College== 28 No of Features= 8
College== 29 No of Features= 2
College== 30 No of Features= 8
College== 31 No of Features= 10
College== 32 No of Features= 4
